from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .core import dump_yaml, load_yaml, persona_dirs, sha256_text, validate_persona


def _lines(values: list[Any]) -> str:
    rendered = []
    for value in values:
        if isinstance(value, dict):
            rendered.append(f"- {value.get('name', value.get('id', '特征'))}: {value.get('behavior', value)}")
        else:
            rendered.append(f"- {value}")
    return "\n".join(rendered)


def compile_prompt(persona: dict[str, Any], examples: dict[str, Any], baselines: list[dict[str, Any]]) -> str:
    traits = persona["personality"]["core_traits"]
    features = persona["features"]
    baseline_rules = [rule for b in baselines for rule in b.get("rules", [])]
    sample = examples.get("examples", [])[:6]
    conversations = "\n\n".join(
        f"用户：{item['user']}\n{persona['name']}：{item['assistant']}" for item in sample
    )
    return f"""# {persona['name']}\n\n## 身份\n{persona['identity']['role']}\n\n{persona['identity']['self_concept']}\n\n## 核心性格\n{_lines(traits)}\n\n## 优点\n{_lines(persona['personality']['strengths'])}\n\n## 缺点\n{_lines(persona['personality']['flaws'])}\n\n## 独特特征\n{_lines(features)}\n\n## 表达方式\n- {persona['voice']['sentence_style']}\n- 默认回复长度：{persona['voice']['default_length']}\n{_lines(persona['voice']['habits'])}\n\n## 避免\n{_lines(persona['voice']['avoid'])}\n\n## 关系与记忆\n{_lines(persona['relationship']['conflict_repair'])}\n{_lines(persona['memory']['never_invent'])}\n\n## 共同边界\n{_lines(baseline_rules)}\n\n## 回复示例\n{conversations}\n"""


def compile_sillytavern(persona: dict[str, Any], examples: dict[str, Any], prompt: str) -> str:
    first = examples.get("examples", [{}])[0].get("assistant", "嗨，今天过得怎么样？")
    card = {
        "spec": "chara_card_v2",
        "spec_version": "2.0",
        "data": {
            "name": persona["name"],
            "description": persona["summary"],
            "personality": prompt,
            "scenario": persona["identity"]["relationship_start"],
            "first_mes": first,
            "mes_example": "\n\n".join(
                f"<START>\n{{{{user}}}}: {e['user']}\n{{{{char}}}}: {e['assistant']}"
                for e in examples.get("examples", [])[:6]
            ),
            "creator_notes": "Generated by CompanionVault",
            "tags": persona.get("tags", []),
            "creator": persona.get("author", {}).get("github", "CompanionVault"),
            "character_version": persona["version"],
            "extensions": {"companion_vault": {"id": persona["id"], "locale": persona["locale"]}},
        },
    }
    return json.dumps(card, ensure_ascii=False, indent=2)


def build_all(root: Path, output: Path) -> dict[str, Any]:
    output.mkdir(parents=True, exist_ok=True)
    registry: dict[str, Any] = {"schema_version": 1, "personas": []}
    for directory in persona_dirs(root):
        errors = validate_persona(directory, root)
        if errors:
            raise ValueError(f"{directory}: " + "; ".join(errors))
        persona = load_yaml(directory / "persona.yaml")
        examples = load_yaml(directory / "examples.yaml")
        baselines = [load_yaml(root / "baselines" / f"{bid}.yaml") for bid in persona.get("baseline", [])]
        prompt = compile_prompt(persona, examples, baselines)
        card = compile_sillytavern(persona, examples, prompt)
        target = output / persona["id"]
        (target / "hermes").mkdir(parents=True, exist_ok=True)
        (target / "generic").mkdir(parents=True, exist_ok=True)
        (target / "sillytavern").mkdir(parents=True, exist_ok=True)
        (target / "hermes/SOUL.md").write_text(prompt, encoding="utf-8")
        (target / "generic/system-prompt.md").write_text(prompt, encoding="utf-8")
        (target / "sillytavern/character.json").write_text(card, encoding="utf-8")
        registry["personas"].append({
            "id": persona["id"], "name": persona["name"], "version": persona["version"],
            "locale": persona["locale"], "summary": persona["summary"], "tags": persona["tags"],
            "files": {
                "hermes": {"path": f"{persona['id']}/hermes/SOUL.md", "sha256": sha256_text(prompt)},
                "generic": {"path": f"{persona['id']}/generic/system-prompt.md", "sha256": sha256_text(prompt)},
                "sillytavern": {"path": f"{persona['id']}/sillytavern/character.json", "sha256": sha256_text(card)},
            },
        })
    registry["personas"].sort(key=lambda p: p["id"])
    (output / "registry.json").write_text(json.dumps(registry, ensure_ascii=False, indent=2), encoding="utf-8")
    return registry
